const Data1 = [
  {
    id: '1',
    title: 'PROGRAMMING GAME UNITY 3D',
    category: 'Most recent',
    Skill: 'Web Development, Front-End Web Development, Computer...',
    price: '$200',
    img: 'https://khoapham.vn/public/images/logo/unity.png',
    desc: 'Build Cross-Platform Games (Web, PC, Mobile) with Unity...',
    View: 'VIEW DETAIL',
    Student: '25',
  },
  {
    id: '2',
    title: 'PROGRAMMING ANDROID',
    category: 'Most view',
    Skill: 'Web Development, Front-End Web Development, Computer...',
    price: '$140',
    img: 'https://khoapham.vn/public/images/logo/android.png',
    desc: 'Providing all Android programming knowledge from A-Z will help you confidently in the Android Programming profession',
    View: 'VIEW DETAIL',
    Student: '35',
  },
  {
    id: '3',
    title: 'PROGRAMMING FLUTTER',
    category: 'Most popular',
    Skill: 'Web Development, Front-End Web Development, Computer...',
    price: '$150',
    img: 'https://khoapham.vn/public/images/logo/flutter.jpg',
    desc: 'Flutter was developed to solve common problems in mobile, Fast Development and Native Performance.',
    View: 'VIEW DETAIL',
    Student: '30',
  },
  {
    id: '4',
    title: 'PROGRAMMING NODEJS',
    category: 'Most popular',
    Skill: 'Web Development, Front-End Web Development, Computer...',
    price: '$100',
    img: 'https://khoapham.vn/public/images/logo/nodejs.png',
    desc: 'NodeJS is an open source, used to build network applications, especially applications that require real time and large request volume.',
    View: 'VIEW DETAIL',
    Student: '22',
  },
  {
    id: '5',
    title: 'PROGRAMMING PHP',
    category: 'The cheapest',
    Skill: 'Web Development, Front-End Web Development, Computer...',
    price: '$30',
    img: 'https://kodesolution.com/html/2016/studypress-html/demo/images/project/4.jpg',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '21',
  },
  {
    id: '6',
    title: 'PROGRAMMING BLOCKCHAIN',
    category: 'Most recent',
    Skill: 'Web Development, Front-End Web Development, Computer...',
    price: '$40',
    img: 'https://khoapham.vn/public/images/khoa-hoc-lap-trinh-game-blockchain/4-mrk.jpeg',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '40',
  },
  {
    id: '7',
    title: 'PROGRAMMING GAME BLOCKCHAIN',
    category: 'Most recent',
    Skill: 'Web Development, Front-End Web Development, Computer...',
    price: '$50',
    img: 'https://khoapham.vn/public/images/logo/blockchain.png',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '30',
  },
  {
    id: '8',
    title: 'NFT PROGRAMMING (NON-FUNGIBLE TOKEN)',
    category: 'Most recent',
    Skill: 'Web Development, Front-End Web Development, Computer...',
    price: '$60',
    img: 'https://khoapham.vn/public/images/nft/khoa-hoc-nft.jpg',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '33',
  },
  {
    id: '9',
    title: 'PROGRAMMING HTML5',
    category: 'Most view',
    Skill: 'Web Development, Front-End Web Development, Computer...',
    price: '$55',
    img: 'https://kodesolution.com/html/2016/studypress-html/demo/images/project/7.jpg',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '40',
  },
  {
    id: '10',
    title: 'BASIC FOREX COURSE & BINARY OPTIONS',
    category: 'Most view',
    Skill: 'Web Development, Front-End Web Development, Computer...',
    price: '$45',
    img: 'https://khoapham.vn/public/images/logo/mean.png',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '15',
  },
]

export default Data1
